<?php

require_once 'Benchmark/Timer.php';

function cmp($cmp, $txt, $o, $l)
{
  return 0 === strcasecmp($cmp, substr($txt, $o, strlen($cmp)));
}
function cmp_u($cmp, $txt, $o, $l)
{
  return mb_strtolower($cmp, "utf-8") === mb_strtolower(substr($txt, $o, strlen($cmp)), 'utf-8');
}
function cmp_pcre($cmp, $txt, $o)
{
  return preg_match('/\G'.preg_quote($cmp).'/i', $txt, $m, 0, $o);
}
function cmp_pcre_u($cmp, $txt, $o)
{
  return preg_match('/\G'.preg_quote($cmp).'/iu', $txt, $m, 0, $o);
}

$text = <<<EOS
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin vel diam est, nec ultrices libero. Sed tristique ultricies ullamcorper. Aenean mollis justo eget nunc mollis vitae condimentum quam ornare. Proin facilisis dui id nulla rhoncus tempus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus quam eros, vulputate quis eleifend luctus, lacinia et massa. Etiam consequat mollis placerat. Maecenas laoreet dignissim magna sed vulputate. Morbi nec erat ullamcorper arcu porta posuere. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque pellentesque malesuada commodo. Nam et felis nisl, a laoreet tellus. Vivamus et pulvinar mauris. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Praesent mattis imperdiet nibh, ac suscipit nunc elementum eget. Cras enim dolor, feugiat sit amet blandit sagittis, faucibus vel diam.

Curabitur eu mauris nec felis scelerisque mollis. Cras volutpat, lectus ut blandit congue, turpis dolor accumsan velit, quis blandit tortor diam vel felis. Nulla et turpis aliquam augue elementum dictum. Sed luctus bibendum felis ut sodales. Sed in mi magna. Nullam laoreet convallis ultrices. Praesent volutpat facilisis vulputate. Sed lacinia aliquam porta. Proin in sapien risus, sed pretium metus. Nam varius magna quis dolor mollis feugiat.

Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Fusce id accumsan orci. Ut ullamcorper, ante vitae interdum luctus, metus arcu vehicula justo, id dictum felis libero quis dui. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Proin malesuada, arcu sed facilisis hendrerit, erat sapien suscipit eros, vel fermentum elit erat hendrerit diam. Nunc mattis posuere sagittis. Aliquam ornare volutpat rhoncus. Aliquam erat volutpat. Fusce sagittis facilisis tempus. Vestibulum pharetra hendrerit vestibulum. Nulla posuere gravida arcu, ultrices ultrices orci varius id. Nullam velit libero, eleifend eget accumsan id, condimentum commodo augue.

Proin porttitor elementum ligula, id dapibus mi luctus ac. Sed adipiscing dui non augue tristique blandit. In id massa mi, et luctus nisi. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Sed tempus leo ac ante porttitor et suscipit nisi dictum. Duis pretium orci eu nisi imperdiet eget dictum libero mollis. Donec cursus aliquam interdum. Nam cursus tincidunt ultrices. Phasellus vel eros ipsum, et blandit nunc. Maecenas lacus nunc, lobortis eget volutpat sed, consequat sit amet enim. Nam a lacus tellus.

In imperdiet augue in tellus lobortis lacinia. Donec posuere imperdiet tellus, id euismod nisl adipiscing vel. Duis sodales augue quis magna ultrices vel tristique tortor rutrum. Sed id ultrices odio. Sed sagittis, turpis non gravida fermentum, diam mauris adipiscing orci, at faucibus eros velit quis purus. Nullam mi velit, pellentesque scelerisque posuere vitae, porta in leo. Cras euismod fermentum neque, ultricies vulputate nulla consequat eu.

Morbi tincidunt nulla in risus placerat malesuada. Vivamus blandit semper mollis. Donec fringilla congue nunc a eleifend. Morbi ornare lectus volutpat lacus posuere ullamcorper. Sed sed massa magna, vitae sagittis tortor. Vestibulum egestas nunc vel diam cursus ac sagittis libero ornare. Nunc commodo vulputate euismod. Nam eu odio et velit rhoncus molestie et quis velit. Pellentesque at est a sem condimentum commodo eu viverra mi. Maecenas feugiat dui ante. Etiam feugiat suscipit risus, nec sodales lorem pellentesque id.

Praesent nisi purus, iaculis at volutpat vel, vulputate in tellus. Nulla a elit eget est auctor placerat quis sit amet orci. Aliquam id neque justo. Cras a ipsum nibh, vel interdum quam. Praesent a leo a ipsum porttitor consequat. Sed egestas auctor nunc. Proin iaculis risus ut nunc vulputate id aliquam metus varius.

Maecenas et purus urna, non blandit velit. Duis id velit quis enim dignissim eleifend. Cras porta mattis mi, ultricies porta urna tristique at. Nunc interdum dapibus purus, sed placerat enim posuere porta. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nam vel tempus ante. Donec suscipit condimentum massa eu gravida. Duis pharetra sollicitudin neque a tempor. Morbi accumsan ornare tincidunt.

Fusce leo arcu, condimentum sit amet congue quis, tempus at eros. Maecenas adipiscing convallis pellentesque. Integer lorem turpis, porta nec faucibus quis, volutpat nec dui. Cras lobortis porta lobortis. Praesent eu mauris a lectus tincidunt pretium eu ac mi. Maecenas pharetra interdum fringilla. Sed ut felis nisl. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Ut facilisis mollis lacus ac posuere. Duis vitae fringilla ipsum. Sed sit amet felis lorem, a iaculis sem. Maecenas in tortor vitae mauris mollis mattis vitae et nisi.

Ut iaculis nulla urna. Fusce éget sem elit. Nullam consectetur leo non lectus condimentum non fermentum tellus aliquam. Morbi odio est, cursus non iaculis a, blandit sed dui. Donec ultricies lobortis tellus id hendrerit. Aliquam urna neque, suscipit at faucibus nec, blandit sed ligula. Donec ut eros turpis. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nunc pharetra feugiat gravida. In hendrerit dapibus lacus tempus tristique. Vivamus laoreet augue ut sem adipiscing bibendum.

Nam vitae dignissim massa. Nulla at nibh et lorem convallis convallis at non orci. Integer a augue in lorem sollicitudin faucibus non at augue. Nam molestie mattis ornare. Praesent diam nisl, lobortis a viverra vitae, vulputate at sapien. Ut lorem turpis, lacinia et pulvinar vel, ornare a nibh. Morbi malesuada vestibulum nunc, vel condimentum orci tincidunt eu. Integer turpis dui, convallis non aliquam rutrum, iaculis a sem. Nam gravida volutpat ligula, in interdum neque feugiat et. In at enim neque, dictum hendrerit nibh. Quisque quis urna nec diam hendrerit luctus. Mauris ac risus arcu, porta fermentum lorem. Cras adipiscing posuere mollis. Suspendisse ut risus justo, at molestie arcu. Fusce eu lectus quis erat malesuada tempor. Curabitur nec ante tellus.

Maecenas tempor, neque scelerisque dignissim iaculis, mauris diam adipiscing augue, id sodales purus libero sit amet nisi. Aliquam suscipit, ipsum a luctus aliquet, ante nisi vulputate enim, vitae ornare dolor mi at quam. Nunc congue purus eget magna porttitor gravida suscipit urna luctus. Duis non lorem sem. Nulla varius porttitor justo. Nulla mattis pulvinar eros ac scelerisque. Pellentesque nec tellus arcu. Nam tincidunt augue non ipsum pellentesque congue. Vivamus a ligula felis, nec sagittis diam. In et ligula at lectus pulvinar rutrum. In bibendum dui et mauris rhoncus sagittis. Pellentesque iaculis laoreet dolor, quis dapibus felis hendrerit facilisis.

Phasellus sollicitudin dictum dui vel iaculis. Etiam hendrerit egestas tortor at venenatis. Phasellus at odio ante. Praesent lacinia luctus augue, sit amet vulputate odio eleifend eu. In interdum molestie sem. Nulla facilisi. Ut quam arcu, convallis a facilisis molestie, tempus nec enim. Nulla placerat porttitor justo eget egestas.

In ante enim, rhoncus vel ullamcorper eu, ornare eu est. Aenean consectetur consequat magna non varius. In hac habitasse platea dictumst. Nulla pellentesque tempor sem quis elementum. Vivamus iaculis diam vitae justo tristique posuere. Morbi nisl arcu, egestas in porta quis, viverra et nulla. Quisque eget lorem arcu. Vivamus eget diam nisl.

Nunc sem enim, accumsan ut imperdiet eu, varius ac velit. Etiam fringilla interdum neque sit amet facilisis. Aenean ut interdum justo. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Aenean tempus mi at mauris vehicula ac aliquam sapien venenatis. Quisque molestie iaculis volutpat. Aenean erat augue, porttitor malesuada viverra vel, tempus malesuada mi. Proin ac auctor magna. Nulla vel ante ipsum. In hendrerit pellentesque est, at eleifend leo laoreet eu. Sed sit amet luctus augue. Vestibulum gravida fermentum nunc, scelerisque vehicula dui ornare nec. Quisque pretium ipsum et nibh egestas tincidunt. Quisque mauris mi, varius mollis pulvinar et, lobortis a lorem.

Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Sed dui nunc, mollis at sollicitudin sed, rhoncus ut ligula. Donec luctus imperdiet mollis. Morbi est est, pharetra sit amet tincidunt vel, vulputate et mauris. Nulla facilisi. In imperdiet enim ac risus sagittis posuere. Mauris sollicitudin ultricies mi, at rutrum lorem suscipit sit amet. Mauris risus ligula, consequat ut lacinia a, scelerisque sit amet tellus.

Fusce condimentum viverra mauris at ultricies. Fusce nec dui arcu. Vivamus a lacus nunc, sit amet hendrerit massa. Curabitur rutrum imperdiet orci, nec suscipit turpis condimentum ac. Aenean volutpat, orci vulputate dictum sagittis, orci urna suscipit lacus, ut dapibus sapien tortor in lacus. Vivamus ullamcorper nibh vitae arcu elementum nec sagittis metus tincidunt. Vivamus aliquet tempor euismod. Nam et est sed eros aliquet accumsan et id velit. Aliquam ac tortor eget elit porta placerat. Suspendisse a risus dolor. Sed euismod augue id quam tempor lacinia. Pellentesque justo neque, sagittis porttitor fringilla imperdiet, lobortis ut risus. Nam tincidunt, felis vehicula rhoncus congue, enim elit congue lacus, a laoreet massa neque at mauris. Aliquam viverra, nulla eget condimentum varius, est sem suscipit sem, sed egestas lorem augue eget felis.

Vestibulum placerat consequat leo vel aliquet. Donec quam dolor, placerat in molestie ac, eleifend nec augue. Cras id metus id quam ullamcorper tincidunt. Etiam neque mi, aliquam id vulputate sed, imperdiet pellentesque lorem. Donec rhoncus nulla quis lorem rutrum posuere. Nullam a leo sapien, nec cursus dui. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Duis vel iaculis augue.

Donec at est metus. Quisque congue, urna vitae tristique viverra, mauris neque adipiscing ligula, ac tincidunt arcu mauris sed justo. Integer metus dui, venenatis non elementum molestie, posuere ut orci. Suspendisse id tempus dolor. Ut vitae nisl eget eros gravida vulputate eget vitae nibh. Sed sapien tellus, adipiscing in rutrum quis, volutpat sed nunc. Sed ut lacus consectetur lacus rhoncus adipiscing non et nunc. Nullam id eros arcu, sit amet adipiscing dui. In pharetra euismod velit quis vulputate. Integer metus arcu, viverra sed pretium sit amet, lacinia non dolor. Vivamus non est eget velit lacinia placerat. Maecenas at nibh mauris, in vulputate urna. Phasellus luctus porttitor nunc non aliquam. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae;

Quisque ut tortor massa, vitae pulvinar libero. Sed ligula risus, dictum sed faucibus ut, fermentum eget lacus. Integer consequat mauris ut diam interdum tincidunt hendrerit nulla semper. Duis vitae feugiat ipsum. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Ut vel accumsan enim. Duis molestie, nulla eget venenatis molestie, massa arcu elementum magna, quis venenatis ipsum ligula eu nulla. Nulla facilisi. Fusce tristique eleifend eleifend. Donec ac eros justo. Aliquam eu urna ac lectus fringilla scelerisque. Aliquam vulputate velit accumsan metus semper consequat. Curabitur velit ipsum, egestas vel euismod ut, eleifend eget lectus. Integer id dui elit. Cras vel hendrerit ante. Ut iaculis porttitor purus ut sagittis.

Proin id nibh erat, posuere pharetra est. Vestibulum sit amet dolor erat. Aliquam erat volutpat. Aliquam auctor sem eget magna consequat vulputate. Integer turpis nisl, iaculis a viverra at, gravida sit amet eros. Mauris ipsum nisl, aliquam eget vulputate a, porttitor in purus. Sed sit amet magna libero, placerat ultricies augue. Duis pharetra quam eu augue vestibulum cursus. Suspendisse adipiscing metus ut nulla ultrices ac iaculis odio laoreet. Maecenas placerat gravida mi. Morbi magna elit, pulvinar ac aliquet eu, tempor in eros. Sed venenatis dui eget nisl pulvinar dignissim imperdiet elit porta.

Donec at lorem est. Suspendisse potenti. Integer vel magna sed nunc dictum sagittis. Morbi placerat lacus ac erat porttitor vestibulum pharetra non elit. Morbi eu elementum erat. Cras nec augue augue, eu tristique nunc. Integer ultrices tempor varius. In id metus odio, ut pellentesque ante.

Sed sit amet lectus nisi, vitae pulvinar dui. Sed sagittis commodo tincidunt. Etiam mollis pulvinar nisl, vitae vestibulum dolor laoreet quis. Mauris in orci ipsum. Aliquam in eros nunc. Duis eget massa hendrerit ligula pharetra placerat. Cras libero massa, mattis ut interdum et, vulputate quis quam. Phasellus ac ultricies lacus. Nulla sollicitudin nisl vel quam pulvinar fringilla. Sed id nibh ligula, eget fermentum massa.

Ut dapibus auctor elit. Donec id metus in tortor auctor pulvinar a in enim. Nulla fermentum rhoncus ligula, at placerat lacus venenatis sit amet. Curabitur porta felis vel odio imperdiet a molestie eros condimentum. Etiam dapibus dolor ut neque viverra vitae aliquet magna venenatis. Pellentesque ac nibh nec mi condimentum pharetra nec non dolor. Etiam suscipit, orci sit amet suscipit sodales, mi tortor dignissim nulla, eget lacinia lacus dolor sit amet dui. Integer suscipit odio id neque commodo lobortis. Nunc aliquet, turpis at sollicitudin consectetur, ipsum arcu aliquam neque, nec convallis purus ipsum at metus. Nunc augue ipsum, rutrum ut placerat convallis, blandit eget mauris. Sed sagittis dui ac turpis tristique at sagittis tellus dignissim. Pellentesque commodo leo tincidunt diam pellentesque volutpat. Vivamus sed turpis a enim dignissim feugiat. Curabitur varius dictum accumsan. Duis et augue dui. Aliquam at nisl libero.

Phasellus varius, turpis vel tempus varius, eros lorem ultricies urna, tincidunt viverra odio augue vitae risus. Nulla sodales, nulla quis lobortis volutpat, justo enim elementum sapien, a lobortis nulla metus a nisi. Ut vel leo a mauris pretium pellentesque bibendum eget tellus. Nulla ornare malesuada iaculis. Quisque pretium purus sit amet magna tempus lacinia. Sed nulla turpis, gravida eu cursus vitae, cursus ornare tortor. Duis tincidunt, leo non eleifend vehicula, lectus est pretium urna, non laoreet quam dui viverra nisi. Ut lacinia commodo magna vel interdum. Fusce eros metus, fringilla euismod dictum eu, scelerisque at nibh. Sed non elit dolor, condimentum posuere est. Integer commodo ornare pretium. Pellentesque accumsan sagittis velit, sagittis pulvinar nibh lobortis vel. Maecenas vel libero lectus, in suscipit lectus. In sollicitudin sem et arcu faucibus aliquam. Nullam tortor augue, luctus nec euismod et, bibendum in ligula. Pellentesque accumsan, dolor at eleifend mollis, lacus urna dapibus ante, vel semper libero massa vitae quam.

Vestibulum porttitor blandit enim volutpat egestas. Maecenas vitae vulputate ante. Quisque pharetra tincidunt quam, nec mattis lacus varius id. Aliquam ipsum arcu, vulputate vitae viverra sed, convallis sit amet nunc. Etiam ullamcorper justo sed ipsum blandit eget placerat lacus iaculis. Etiam tristique tincidunt viverra. Proin ut leo ipsum, id consequat augue. Nullam eget eros massa. Nulla rutrum metus ac massa facilisis ac bibendum enim condimentum. Cras at tellus enim. Nam placerat luctus urna et pharetra. In hac habitasse platea dictumst.

Aliquam lectus ante, pulvinar id pulvinar vel, bibendum vitae est. Quisque posuere, arcu quis sagittis volutpat, sem quam pretium dui, id eleifend justo eros eget magna. Proin gravida tincidunt nisi tincidunt aliquet. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec dui risus, viverra a euismod sit amet, consectetur in lacus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Mauris ipsum diam, tempor id dictum nec, condimentum a felis. Etiam in massa sem. Donec ante lacus, porttitor at tincidunt nec, venenatis eget sem. Praesent quis urna mi.

Donec nec tellus ut enim sodales facilisis. Nulla urna lorem, volutpat ac adipiscing non, tincidunt eu odio. Nullam felis tortor, tincidunt vel elementum id, sagittis vel nisl. Aliquam rhoncus, ante fringilla feugiat facilisis, dui quam tempus nibh, ac consectetur nulla risus sed est. Nunc tempor lobortis facilisis. Ut tempus nisi nec elit varius iaculis. Proin mi dui, ultricies lacinia viverra vel, rutrum id orci. Proin eleifend nisi sed eros pulvinar ac auctor purus eleifend. Etiam eu ante eu dolor adipiscing ornare. Sed sollicitudin arcu enim. Donec lacus eros, imperdiet id rhoncus a, luctus mattis dolor. Vestibulum justo ipsum, tempor nec bibendum nec, convallis ut ante. Vestibulum aliquet, lectus et pretium varius, lacus dui bibendum sapien, a dictum nunc sem non mauris. Suspendisse in diam lacus. Nulla vel tellus a ipsum rutrum faucibus a sed dolor.

Maecenas eu sem in purus tristique dictum. Proin vestibulum nibh sed erat laoreet eget feugiat felis luctus. Suspendisse congue accumsan justo sed blandit. Cras suscipit dui vitae massa luctus at elementum risus semper. Phasellus blandit vestibulum consequat. Nam ut convallis ipsum. Aliquam malesuada augue non nisl consectetur eu semper massa tincidunt. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Sed purus nisl, auctor et suscipit sed, pharetra quis nibh. Cras quis erat dolor.

Nullam lectus sapien, mollis vel consequat et, sodales at neque. Sed semper erat non odio consectetur vitae lacinia est condimentum. Ut posuere scelerisque nisl, congue lobortis risus placerat nec. Vivamus eget magna sem. Donec bibendum faucibus tincidunt. Quisque ornare porttitor tortor sit amet molestie. Maecenas mattis imperdiet facilisis. Vestibulum ornare enim vel justo gravida pharetra. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum eleifend euismod lacus, at viverra orci dapibus eu. Quisque aliquam molestie aliquam.

Nullam aliquam velit eget ante eleifend congue. Sed ac enim nisl. Nulla semper sollicitudin felis, vel dignissim tellus commodo ac. Sed imperdiet elementum euismod. Mauris eu nisi ac lectus convallis cursus eu nec ligula. Proin tristique est vel massa scelerisque tristique. Ut malesuada placerat congue. Sed pretium fermentum ligula, ut ultrices felis faucibus eu.

Sed at lacus nibh, a interdum eros. In sit amet felis felis. Sed eget iaculis velit. Etiam sollicitudin pretium nunc et fringilla. Nunc ligula lorem, accumsan vel porta at, porttitor quis felis. Etiam cursus elit at velit pretium sit amet gravida enim tincidunt. Phasellus laoreet tellus neque. Duis ac nibh sit amet lorem ullamcorper accumsan sit amet pharetra felis. Fusce fermentum purus lacus, eget interdum ante.

Etiam sed dui quis dolor tincidunt eleifend. Morbi vitae tortor eget nisi tristique dictum. Vivamus sit amet faucibus ante. Sed molestie lectus vel tortor mollis placerat. Mauris iaculis congue orci eget eleifend. Morbi risus tellus, sodales pellentesque malesuada vitae, tempus id enim. Etiam sed sem magna. Nam porttitor laoreet eros eget ullamcorper. Sed vulputate aliquet neque in malesuada. Praesent commodo, quam non sagittis tincidunt, leo tellus sollicitudin sem, sagittis suscipit nisl dolor et urna.

Vestibulum eget ante sapien, vel venenatis massa. Quisque sollicitudin tristique purus id rutrum. Integer at risus non ipsum dictum facilisis id sed erat. Donec dictum mauris et neque vehicula ac fermentum nisl sodales. Praesent accumsan venenatis nibh. Cras ac sollicitudin neque. Vivamus ornare dolor eu nulla posuere ut vehicula massa vulputate. Ut sit amet sapien in magna semper feugiat. Suspendisse rutrum scelerisque laoreet. In ac nisi vehicula nisi congue vulputate non in purus. Sed lacus justo, sodales ac tincidunt convallis, sodales vitae mauris. Duis tortor justo, condimentum quis faucibus eu, fermentum eget leo. Nunc hendrerit nisl vel urna accumsan in placerat libero faucibus. Sed vitae risus nec augue tincidunt aliquam sed a enim. Sed a tempus ligula. Donec dignissim tristique adipiscing.

Maecenas quis convallis lacus. In eget metus ligula. Vivamus interdum turpis ac mauris feugiat ac faucibus nisi dignissim. Maecenas malesuada pellentesque diam vel euismod. Nam volutpat, tortor ut lacinia varius, purus diam hendrerit augue, non fermentum enim quam sed nisl. Donec eget massa diam, a aliquet neque. Praesent tincidunt, ligula eu bibendum sodales, sapien lectus porttitor nisl, sit amet fringilla ante magna in nulla. Ut faucibus suscipit ligula, at cursus quam congue nec. Nulla quam tortor, pretium at faucibus id, pulvinar at urna. Integer elementum tortor non libero varius in euismod leo eleifend. Phasellus mattis consequat tristique. Quisque non lacus eu quam porta molestie at ut tellus. Fusce iaculis mi ut quam egestas in cursus turpis congue. Donec tristique ornare enim, et mattis lorem luctus at. Nulla fermentum eros ac turpis sollicitudin quis tincidunt lorem venenatis. Phasellus quis odio velit.

Maecenas et urna sit amet risus commodo molestie vel eu felis. Ut faucibus hendrerit nisi, sit amet volutpat purus ullamcorper vel. Vestibulum arcu ligula, gravida vel tempor quis, bibendum ultrices metus. Morbi varius dui sit amet mi dictum malesuada. Fusce et ullamcorper tortor. Nam arcu tellus, dignissim id feugiat quis, pharetra eget nibh. Nullam justo erat, lacinia id mollis sit amet, venenatis in dui. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Maecenas sit amet dolor vitae lacus imperdiet posuere ornare eget ante. In ultricies lacinia mauris ut egestas. Sed viverra, urna at pellentesque pharetra, urna magna tincidunt augue, a lacinia odio dui quis odio. Aliquam erat volutpat. Quisque fermentum feugiat egestas. Quisque rutrum ultrices facilisis. Nam vitae orci non justo ullamcorper rhoncus.

Phasellus blandit vestibulum aliquet. In volutpat, urna non interdum porta, dui lacus tempor dui, eu pellentesque nisl lorem nec tellus. Suspendisse gravida, sem et aliquet euismod, lacus erat facilisis diam, egestas fringilla massa mi auctor augue. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. In sit amet tortor a lorem vestibulum pellentesque. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Integer tempus lorem non purus tristique tristique. In bibendum nulla enim. Praesent interdum, justo vitae cursus malesuada, urna lacus eleifend eros, eu consectetur nunc quam eu mi. Fusce ipsum est, molestie at pellentesque sit amet, rutrum at libero. Donec hendrerit mattis massa, eget fringilla orci pretium quis. Fusce fringilla placerat pharetra. Proin varius laoreet ullamcorper. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.

Vestibulum tincidunt lectus et nisi mattis vitae vulputate magna hendrerit. Fusce sodales, dolor in sodales elementum, arcu eros fringilla turpis, sed viverra mauris diam id tellus. Pellentesque eget mollis nisl. Suspendisse lacus metus, aliquam in ornare sed, eleifend euismod libero. Praesent nec odio orci. Phasellus pretium neque in ipsum suscipit tincidunt. Aenean id viverra lectus. Integer sagittis, nulla vitae mattis convallis, enim nisi sodales tortor, in venenatis libero nisi eget augue. Nam ut semper quam. Nunc arcu orci, ultrices sit amet rhoncus quis, condimentum non neque. Nunc dictum vehicula neque, ut tincidunt nisi vehicula vel. Cras malesuada nisi consectetur lorem varius pellentesque. Nam mauris mi, gravida et eleifend in, gravida pretium mauris. Aenean rutrum nisi a lectus consequat auctor.

Aenean suscipit odio nec enim semper pharetra. Proin lobortis augue at lectus suscipit laoreet sit amet nec velit. Etiam eu risus sed dui rutrum blandit. Aliquam commodo sodales massa, nec pulvinar elit rhoncus ac. Cras sollicitudin sollicitudin velit, sit amet tincidunt nisl fermentum ut. Ut a est vel ante volutpat tristique eget in tortor. Sed nec mi et neque lacinia tempus eu id lacus. Praesent tincidunt tincidunt dui, quis pharetra urna accumsan sed.

Pellentesque ac diam non odio blandit ullamcorper nec ac orci. Morbi eu sapien sit amet erat interdum egestas a non erat. Suspendisse consequat velit eget sem posuere non venenatis tellus dapibus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vivamus faucibus nisi a felis sollicitudin eget dictum nisl lobortis. Morbi vitae sagittis ante. Nullam sit amet dapibus purus. Fusce convallis dapibus nisl at hendrerit. In hac habitasse platea dictumst. Maecenas faucibus metus luctus sapien tincidunt cursus. Sed at augue dolor. Curabitur condimentum, risus nec egestas bibendum, tortor erat ultrices massa, vel sollicitudin nibh erat vitae dolor.

Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Aliquam erat volutpat. Ut dapibus condimentum mauris ac aliquet. Aenean at arcu velit, quis pellentesque turpis. Vivamus elementum lacinia eros in porttitor. Ut aliquam mauris non nulla pulvinar iaculis. Maecenas eget faucibus nisi. Curabitur rutrum ultrices pharetra. In rutrum vulputate sapien vel eleifend. Sed id feugiat ante. Quisque viverra arcu eget nunc vestibulum a lobortis velit dignissim. Pellentesque vitae velit tempus diam venenatis consectetur. Sed nec risus sit amet purus semper dictum in non purus. Curabitur semper, enim et semper mattis, mauris elit rutrum risus, vitae sollicitudin orci nibh eget urna. Quisque at dapibus sapien. Maecenas turpis justo, pellentesque nec fermentum vel, tristique sed tortor.

Morbi in consectetur tellus. Maecenas id justo non orci suscipit placerat. Duis lectus diam, tincidunt sed convallis a, malesuada id diam. Sed vestibulum cursus leo. Vivamus egestas mauris non elit porttitor a ornare dui placerat. Vivamus eu ligula ut massa gravida adipiscing ac in velit. Vestibulum nec ligula lectus, eu ornare sapien. Vestibulum vel quam et nulla cursus ornare sit amet vel augue. Aenean quis lacus nisi. Ut vestibulum tempus lectus sit amet eleifend. Duis sit amet metus eu nisl lacinia fringilla sit amet a tortor. Quisque tristique justo eget massa tempor id pharetra lacus elementum.

Ut at diam et arcu egestas pulvinar. Aliquam tincidunt nisl et libero elementum id suscipit nulla fringilla. Mauris velit sem, pharetra nec luctus nec, ullamcorper id felis. Ut tempus congue diam in sodales. Pellentesque non elit eros. Vivamus sit amet lorem a eros pellentesque euismod ac ut urna. Donec vitae nulla venenatis tellus dignissim fermentum. Donec congue porttitor massa, in egestas massa fermentum vel. Mauris suscipit porttitor fermentum. Phasellus arcu ligula, mattis ac auctor et, sollicitudin cursus lectus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Cras mattis fringilla nisi, vitae molestie ante facilisis ornare. Pellentesque ligula arcu, ultricies eget hendrerit sed, fermentum egestas libero. Mauris porta condimentum feugiat. Nulla facilisi.

Quisque tempor, nisl in porta pretium, mauris purus volutpat lectus, a condimentum ante odio eu diam. Sed augue diam, pellentesque nec pellentesque at, lacinia sed ante. In mollis facilisis vestibulum. Pellentesque vel tortor at arcu laoreet consectetur at in libero. Donec vitae ligula lacus. Pellentesque non ultricies arcu. Aliquam volutpat facilisis dictum. Morbi cursus varius scelerisque. Aliquam dictum mauris nec turpis tincidunt non iaculis leo mollis. Integer luctus sapien non metus ullamcorper ut laoreet est laoreet. Donec feugiat mattis lectus, et tristique tortor malesuada at. Maecenas rhoncus libero nec diam lobortis auctor. Praesent dapibus pulvinar pellentesque.

Sed luctus fermentum velit at sagittis. Nunc placerat semper sagittis. Donec sit amet mi at turpis posuere aliquet id vel sapien. Nunc at ligula eget erat sagittis ultrices at sed erat. Cras vitae sem ut neque fermentum consectetur. Suspendisse eros dolor, posuere in eleifend id, ullamcorper iaculis mauris. Cras luctus augue vel felis dignissim venenatis.

Curabitur ut elit ac sapien congue lacinia at sit amet metus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Ut non odio eget sem elementum sodales. Etiam auctor consectetur lacus, at elementum erat hendrerit eget. Suspendisse sed leo in massa rutrum malesuada in eget urna. Nunc ac magna justo, non venenatis sem. Sed eu enim metus, at consectetur ipsum. In vel est tellus, at egestas purus. Cras tempus varius metus, sed ullamcorper sem cursus eu. Nullam a turpis enim, vel volutpat mauris. Praesent dapibus facilisis dolor, sed laoreet nunc tristique quis. Curabitur non viverra augue. Nullam ornare, lectus a sollicitudin molestie, nibh purus ullamcorper augue, a tincidunt elit massa vel libero. Fusce consequat ligula sed risus commodo non ultrices purus mattis. Sed lacinia mollis est, sollicitudin accumsan magna gravida eu. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.

Pellentesque aliquet sodales felis sed bibendum. Vestibulum eleifend odio id tortor vehicula posuere. Suspendisse vel sem mi, ac pulvinar ipsum. Sed id felis ante, eu convallis erat. Etiam ac faucibus lectus. Ut euismod, leo sit amet porttitor lacinia, orci est aliquet eros, vel scelerisque elit nulla vel neque. Curabitur sed sapien nunc. Nunc consectetur sagittis arcu sed vestibulum. Aenean suscipit malesuada interdum. Nulla facilisi. Mauris nec tortor sed sem condimentum egestas.

Nulla facilisi. Nam quis ultricies leo. Sed eu mauris lorem. Quisque at nibh ligula. Ut non ante quis felis molestie scelerisque. Praesent vitae bibendum libero. Sed augue leo, sollicitudin a viverra consequat, rhoncus in dolor. Nulla condimentum, sem vel vehicula pretium, massa nulla volutpat erat, non malesuada mauris diam at diam. Praesent a eros leo.

Donec molestie nulla a orci convallis congue. Quisque auctor, lorem sed ultrices congue, nisl est pellentesque nunc, ut aliquam sapien turpis quis metus. Phasellus sed ipsum dui, at sollicitudin dui. In augue sem, molestie vitae sollicitudin gravida, elementum vitae urna. Pellentesque malesuada, felis eu porttitor eleifend, nulla neque luctus nulla, vitae pellentesque magna urna nec nulla. Pellentesque suscipit condimentum mauris, sit amet tempus diam pharetra et. Duis malesuada velit id urna gravida aliquet. Curabitur iaculis leo quis nisl porta ut accumsan urna rhoncus. Ut sed egestas diam. Nulla lobortis, tortor sit amet rutrum aliquam, tortor felis fermentum odio, non eleifend purus leo sit amet est. Vivamus sit amet eros odio.

Curabitur molestie, elit ut eleifend imperdiet, lacus nulla cursus est, vel tristique purus lorem at massa. Suspendisse tristique commodo lobortis. Morbi cursus tempus metus vitae mollis. Curabitur laoreet magna a erat luctus sed volutpat risus dictum. Aliquam nisl nisl, porta a placerat ut, eleifend eget sem. Sed sem ipsum, molestie in porttitor ut, semper vel leo. Nam ac mattis sapien. Proin aliquet laoreet volutpat. Maecenas lobortis iaculis dolor, quis porta purus consequat ut. 

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin vel diam est, nec ultrices libero. Sed tristique ultricies ullamcorper. Aenean mollis justo eget nunc mollis vitae condimentum quam ornare. Proin facilisis dui id nulla rhoncus tempus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus quam eros, vulputate quis eleifend luctus, lacinia et massa. Etiam consequat mollis placerat. Maecenas laoreet dignissim magna sed vulputate. Morbi nec erat ullamcorper arcu porta posuere. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque pellentesque malesuada commodo. Nam et felis nisl, a laoreet tellus. Vivamus et pulvinar mauris. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Praesent mattis imperdiet nibh, ac suscipit nunc elementum eget. Cras enim dolor, feugiat sit amet blandit sagittis, faucibus vel diam.

Curabitur eu mauris nec felis scelerisque mollis. Cras volutpat, lectus ut blandit congue, turpis dolor accumsan velit, quis blandit tortor diam vel felis. Nulla et turpis aliquam augue elementum dictum. Sed luctus bibendum felis ut sodales. Sed in mi magna. Nullam laoreet convallis ultrices. Praesent volutpat facilisis vulputate. Sed lacinia aliquam porta. Proin in sapien risus, sed pretium metus. Nam varius magna quis dolor mollis feugiat.

Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Fusce id accumsan orci. Ut ullamcorper, ante vitae interdum luctus, metus arcu vehicula justo, id dictum felis libero quis dui. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Proin malesuada, arcu sed facilisis hendrerit, erat sapien suscipit eros, vel fermentum elit erat hendrerit diam. Nunc mattis posuere sagittis. Aliquam ornare volutpat rhoncus. Aliquam erat volutpat. Fusce sagittis facilisis tempus. Vestibulum pharetra hendrerit vestibulum. Nulla posuere gravida arcu, ultrices ultrices orci varius id. Nullam velit libero, eleifend eget accumsan id, condimentum commodo augue.

Proin porttitor elementum ligula, id dapibus mi luctus ac. Sed adipiscing dui non augue tristique blandit. In id massa mi, et luctus nisi. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Sed tempus leo ac ante porttitor et suscipit nisi dictum. Duis pretium orci eu nisi imperdiet eget dictum libero mollis. Donec cursus aliquam interdum. Nam cursus tincidunt ultrices. Phasellus vel eros ipsum, et blandit nunc. Maecenas lacus nunc, lobortis eget volutpat sed, consequat sit amet enim. Nam a lacus tellus.

In imperdiet augue in tellus lobortis lacinia. Donec posuere imperdiet tellus, id euismod nisl adipiscing vel. Duis sodales augue quis magna ultrices vel tristique tortor rutrum. Sed id ultrices odio. Sed sagittis, turpis non gravida fermentum, diam mauris adipiscing orci, at faucibus eros velit quis purus. Nullam mi velit, pellentesque scelerisque posuere vitae, porta in leo. Cras euismod fermentum neque, ultricies vulputate nulla consequat eu.

Morbi tincidunt nulla in risus placerat malesuada. Vivamus blandit semper mollis. Donec fringilla congue nunc a eleifend. Morbi ornare lectus volutpat lacus posuere ullamcorper. Sed sed massa magna, vitae sagittis tortor. Vestibulum egestas nunc vel diam cursus ac sagittis libero ornare. Nunc commodo vulputate euismod. Nam eu odio et velit rhoncus molestie et quis velit. Pellentesque at est a sem condimentum commodo eu viverra mi. Maecenas feugiat dui ante. Etiam feugiat suscipit risus, nec sodales lorem pellentesque id.

Praesent nisi purus, iaculis at volutpat vel, vulputate in tellus. Nulla a elit eget est auctor placerat quis sit amet orci. Aliquam id neque justo. Cras a ipsum nibh, vel interdum quam. Praesent a leo a ipsum porttitor consequat. Sed egestas auctor nunc. Proin iaculis risus ut nunc vulputate id aliquam metus varius.

Maecenas et purus urna, non blandit velit. Duis id velit quis enim dignissim eleifend. Cras porta mattis mi, ultricies porta urna tristique at. Nunc interdum dapibus purus, sed placerat enim posuere porta. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nam vel tempus ante. Donec suscipit condimentum massa eu gravida. Duis pharetra sollicitudin neque a tempor. Morbi accumsan ornare tincidunt.

Fusce leo arcu, condimentum sit amet congue quis, tempus at eros. Maecenas adipiscing convallis pellentesque. Integer lorem turpis, porta nec faucibus quis, volutpat nec dui. Cras lobortis porta lobortis. Praesent eu mauris a lectus tincidunt pretium eu ac mi. Maecenas pharetra interdum fringilla. Sed ut felis nisl. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Ut facilisis mollis lacus ac posuere. Duis vitae fringilla ipsum. Sed sit amet felis lorem, a iaculis sem. Maecenas in tortor vitae mauris mollis mattis vitae et nisi.

Ut iaculis nulla urna. Fusce eget sem elit. Nullam consectetur leo non lectus condimentum non fermentum tellus aliquam. Morbi odio est, cursus non iaculis a, blandit sed dui. Donec ultricies lobortis tellus id hendrerit. Aliquam urna neque, suscipit at faucibus nec, blandit sed ligula. Donec ut eros turpis. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nunc pharetra feugiat gravida. In hendrerit dapibus lacus tempus tristique. Vivamus laoreet augue ut sem adipiscing bibendum.

Nam vitae dignissim massa. Nulla at nibh et lorem convallis convallis at non orci. Integer a augue in lorem sollicitudin faucibus non at augue. Nam molestie mattis ornare. Praesent diam nisl, lobortis a viverra vitae, vulputate at sapien. Ut lorem turpis, lacinia et pulvinar vel, ornare a nibh. Morbi malesuada vestibulum nunc, vel condimentum orci tincidunt eu. Integer turpis dui, convallis non aliquam rutrum, iaculis a sem. Nam gravida volutpat ligula, in interdum neque feugiat et. In at enim neque, dictum hendrerit nibh. Quisque quis urna nec diam hendrerit luctus. Mauris ac risus arcu, porta fermentum lorem. Cras adipiscing posuere mollis. Suspendisse ut risus justo, at molestie arcu. Fusce eu lectus quis erat malesuada tempor. Curabitur nec ante tellus.

Maecenas tempor, neque scelerisque dignissim iaculis, mauris diam adipiscing augue, id sodales purus libero sit amet nisi. Aliquam suscipit, ipsum a luctus aliquet, ante nisi vulputate enim, vitae ornare dolor mi at quam. Nunc congue purus eget magna porttitor gravida suscipit urna luctus. Duis non lorem sem. Nulla varius porttitor justo. Nulla mattis pulvinar eros ac scelerisque. Pellentesque nec tellus arcu. Nam tincidunt augue non ipsum pellentesque congue. Vivamus a ligula felis, nec sagittis diam. In et ligula at lectus pulvinar rutrum. In bibendum dui et mauris rhoncus sagittis. Pellentesque iaculis laoreet dolor, quis dapibus felis hendrerit facilisis.

Phasellus sollicitudin dictum dui vel iaculis. Etiam hendrerit egestas tortor at venenatis. Phasellus at odio ante. Praesent lacinia luctus augue, sit amet vulputate odio eleifend eu. In interdum molestie sem. Nulla facilisi. Ut quam arcu, convallis a facilisis molestie, tempus nec enim. Nulla placerat porttitor justo eget egestas.

In ante enim, rhoncus vel ullamcorper eu, ornare eu est. Aenean consectetur consequat magna non varius. In hac habitasse platea dictumst. Nulla pellentesque tempor sem quis elementum. Vivamus iaculis diam vitae justo tristique posuere. Morbi nisl arcu, egestas in porta quis, viverra et nulla. Quisque eget lorem arcu. Vivamus eget diam nisl.

Nunc sem enim, accumsan ut imperdiet eu, varius ac velit. Etiam fringilla interdum neque sit amet facilisis. Aenean ut interdum justo. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Aenean tempus mi at mauris vehicula ac aliquam sapien venenatis. Quisque molestie iaculis volutpat. Aenean erat augue, porttitor malesuada viverra vel, tempus malesuada mi. Proin ac auctor magna. Nulla vel ante ipsum. In hendrerit pellentesque est, at eleifend leo laoreet eu. Sed sit amet luctus augue. Vestibulum gravida fermentum nunc, scelerisque vehicula dui ornare nec. Quisque pretium ipsum et nibh egestas tincidunt. Quisque mauris mi, varius mollis pulvinar et, lobortis a lorem.

Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Sed dui nunc, mollis at sollicitudin sed, rhoncus ut ligula. Donec luctus imperdiet mollis. Morbi est est, pharetra sit amet tincidunt vel, vulputate et mauris. Nulla facilisi. In imperdiet enim ac risus sagittis posuere. Mauris sollicitudin ultricies mi, at rutrum lorem suscipit sit amet. Mauris risus ligula, consequat ut lacinia a, scelerisque sit amet tellus.

Fusce condimentum viverra mauris at ultricies. Fusce nec dui arcu. Vivamus a lacus nunc, sit amet hendrerit massa. Curabitur rutrum imperdiet orci, nec suscipit turpis condimentum ac. Aenean volutpat, orci vulputate dictum sagittis, orci urna suscipit lacus, ut dapibus sapien tortor in lacus. Vivamus ullamcorper nibh vitae arcu elementum nec sagittis metus tincidunt. Vivamus aliquet tempor euismod. Nam et est sed eros aliquet accumsan et id velit. Aliquam ac tortor eget elit porta placerat. Suspendisse a risus dolor. Sed euismod augue id quam tempor lacinia. Pellentesque justo neque, sagittis porttitor fringilla imperdiet, lobortis ut risus. Nam tincidunt, felis vehicula rhoncus congue, enim elit congue lacus, a laoreet massa neque at mauris. Aliquam viverra, nulla eget condimentum varius, est sem suscipit sem, sed egestas lorem augue eget felis.

Vestibulum placerat consequat leo vel aliquet. Donec quam dolor, placerat in molestie ac, eleifend nec augue. Cras id metus id quam ullamcorper tincidunt. Etiam neque mi, aliquam id vulputate sed, imperdiet pellentesque lorem. Donec rhoncus nulla quis lorem rutrum posuere. Nullam a leo sapien, nec cursus dui. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Duis vel iaculis augue.

Donec at est metus. Quisque congue, urna vitae tristique viverra, mauris neque adipiscing ligula, ac tincidunt arcu mauris sed justo. Integer metus dui, venenatis non elementum molestie, posuere ut orci. Suspendisse id tempus dolor. Ut vitae nisl eget eros gravida vulputate eget vitae nibh. Sed sapien tellus, adipiscing in rutrum quis, volutpat sed nunc. Sed ut lacus consectetur lacus rhoncus adipiscing non et nunc. Nullam id eros arcu, sit amet adipiscing dui. In pharetra euismod velit quis vulputate. Integer metus arcu, viverra sed pretium sit amet, lacinia non dolor. Vivamus non est eget velit lacinia placerat. Maecenas at nibh mauris, in vulputate urna. Phasellus luctus porttitor nunc non aliquam. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae;

Quisque ut tortor massa, vitae pulvinar libero. Sed ligula risus, dictum sed faucibus ut, fermentum eget lacus. Integer consequat mauris ut diam interdum tincidunt hendrerit nulla semper. Duis vitae feugiat ipsum. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Ut vel accumsan enim. Duis molestie, nulla eget venenatis molestie, massa arcu elementum magna, quis venenatis ipsum ligula eu nulla. Nulla facilisi. Fusce tristique eleifend eleifend. Donec ac eros justo. Aliquam eu urna ac lectus fringilla scelerisque. Aliquam vulputate velit accumsan metus semper consequat. Curabitur velit ipsum, egestas vel euismod ut, eleifend eget lectus. Integer id dui elit. Cras vel hendrerit ante. Ut iaculis porttitor purus ut sagittis.

Proin id nibh erat, posuere pharetra est. Vestibulum sit amet dolor erat. Aliquam erat volutpat. Aliquam auctor sem eget magna consequat vulputate. Integer turpis nisl, iaculis a viverra at, gravida sit amet eros. Mauris ipsum nisl, aliquam eget vulputate a, porttitor in purus. Sed sit amet magna libero, placerat ultricies augue. Duis pharetra quam eu augue vestibulum cursus. Suspendisse adipiscing metus ut nulla ultrices ac iaculis odio laoreet. Maecenas placerat gravida mi. Morbi magna elit, pulvinar ac aliquet eu, tempor in eros. Sed venenatis dui eget nisl pulvinar dignissim imperdiet elit porta.

Donec at lorem est. Suspendisse potenti. Integer vel magna sed nunc dictum sagittis. Morbi placerat lacus ac erat porttitor vestibulum pharetra non elit. Morbi eu elementum erat. Cras nec augue augue, eu tristique nunc. Integer ultrices tempor varius. In id metus odio, ut pellentesque ante.

Sed sit amet lectus nisi, vitae pulvinar dui. Sed sagittis commodo tincidunt. Etiam mollis pulvinar nisl, vitae vestibulum dolor laoreet quis. Mauris in orci ipsum. Aliquam in eros nunc. Duis eget massa hendrerit ligula pharetra placerat. Cras libero massa, mattis ut interdum et, vulputate quis quam. Phasellus ac ultricies lacus. Nulla sollicitudin nisl vel quam pulvinar fringilla. Sed id nibh ligula, eget fermentum massa.

Ut dapibus auctor elit. Donec id metus in tortor auctor pulvinar a in enim. Nulla fermentum rhoncus ligula, at placerat lacus venenatis sit amet. Curabitur porta felis vel odio imperdiet a molestie eros condimentum. Etiam dapibus dolor ut neque viverra vitae aliquet magna venenatis. Pellentesque ac nibh nec mi condimentum pharetra nec non dolor. Etiam suscipit, orci sit amet suscipit sodales, mi tortor dignissim nulla, eget lacinia lacus dolor sit amet dui. Integer suscipit odio id neque commodo lobortis. Nunc aliquet, turpis at sollicitudin consectetur, ipsum arcu aliquam neque, nec convallis purus ipsum at metus. Nunc augue ipsum, rutrum ut placerat convallis, blandit eget mauris. Sed sagittis dui ac turpis tristique at sagittis tellus dignissim. Pellentesque commodo leo tincidunt diam pellentesque volutpat. Vivamus sed turpis a enim dignissim feugiat. Curabitur varius dictum accumsan. Duis et augue dui. Aliquam at nisl libero.

Phasellus varius, turpis vel tempus varius, eros lorem ultricies urna, tincidunt viverra odio augue vitae risus. Nulla sodales, nulla quis lobortis volutpat, justo enim elementum sapien, a lobortis nulla metus a nisi. Ut vel leo a mauris pretium pellentesque bibendum eget tellus. Nulla ornare malesuada iaculis. Quisque pretium purus sit amet magna tempus lacinia. Sed nulla turpis, gravida eu cursus vitae, cursus ornare tortor. Duis tincidunt, leo non eleifend vehicula, lectus est pretium urna, non laoreet quam dui viverra nisi. Ut lacinia commodo magna vel interdum. Fusce eros metus, fringilla euismod dictum eu, scelerisque at nibh. Sed non elit dolor, condimentum posuere est. Integer commodo ornare pretium. Pellentesque accumsan sagittis velit, sagittis pulvinar nibh lobortis vel. Maecenas vel libero lectus, in suscipit lectus. In sollicitudin sem et arcu faucibus aliquam. Nullam tortor augue, luctus nec euismod et, bibendum in ligula. Pellentesque accumsan, dolor at eleifend mollis, lacus urna dapibus ante, vel semper libero massa vitae quam.

Vestibulum porttitor blandit enim volutpat egestas. Maecenas vitae vulputate ante. Quisque pharetra tincidunt quam, nec mattis lacus varius id. Aliquam ipsum arcu, vulputate vitae viverra sed, convallis sit amet nunc. Etiam ullamcorper justo sed ipsum blandit eget placerat lacus iaculis. Etiam tristique tincidunt viverra. Proin ut leo ipsum, id consequat augue. Nullam eget eros massa. Nulla rutrum metus ac massa facilisis ac bibendum enim condimentum. Cras at tellus enim. Nam placerat luctus urna et pharetra. In hac habitasse platea dictumst.

Aliquam lectus ante, pulvinar id pulvinar vel, bibendum vitae est. Quisque posuere, arcu quis sagittis volutpat, sem quam pretium dui, id eleifend justo eros eget magna. Proin gravida tincidunt nisi tincidunt aliquet. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec dui risus, viverra a euismod sit amet, consectetur in lacus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Mauris ipsum diam, tempor id dictum nec, condimentum a felis. Etiam in massa sem. Donec ante lacus, porttitor at tincidunt nec, venenatis eget sem. Praesent quis urna mi.

Donec nec tellus ut enim sodales facilisis. Nulla urna lorem, volutpat ac adipiscing non, tincidunt eu odio. Nullam felis tortor, tincidunt vel elementum id, sagittis vel nisl. Aliquam rhoncus, ante fringilla feugiat facilisis, dui quam tempus nibh, ac consectetur nulla risus sed est. Nunc tempor lobortis facilisis. Ut tempus nisi nec elit varius iaculis. Proin mi dui, ultricies lacinia viverra vel, rutrum id orci. Proin eleifend nisi sed eros pulvinar ac auctor purus eleifend. Etiam eu ante eu dolor adipiscing ornare. Sed sollicitudin arcu enim. Donec lacus eros, imperdiet id rhoncus a, luctus mattis dolor. Vestibulum justo ipsum, tempor nec bibendum nec, convallis ut ante. Vestibulum aliquet, lectus et pretium varius, lacus dui bibendum sapien, a dictum nunc sem non mauris. Suspendisse in diam lacus. Nulla vel tellus a ipsum rutrum faucibus a sed dolor.

Maecenas eu sem in purus tristique dictum. Proin vestibulum nibh sed erat laoreet eget feugiat felis luctus. Suspendisse congue accumsan justo sed blandit. Cras suscipit dui vitae massa luctus at elementum risus semper. Phasellus blandit vestibulum consequat. Nam ut convallis ipsum. Aliquam malesuada augue non nisl consectetur eu semper massa tincidunt. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Sed purus nisl, auctor et suscipit sed, pharetra quis nibh. Cras quis erat dolor.

Nullam lectus sapien, mollis vel consequat et, sodales at neque. Sed semper erat non odio consectetur vitae lacinia est condimentum. Ut posuere scelerisque nisl, congue lobortis risus placerat nec. Vivamus eget magna sem. Donec bibendum faucibus tincidunt. Quisque ornare porttitor tortor sit amet molestie. Maecenas mattis imperdiet facilisis. Vestibulum ornare enim vel justo gravida pharetra. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum eleifend euismod lacus, at viverra orci dapibus eu. Quisque aliquam molestie aliquam.

Nullam aliquam velit eget ante eleifend congue. Sed ac enim nisl. Nulla semper sollicitudin felis, vel dignissim tellus commodo ac. Sed imperdiet elementum euismod. Mauris eu nisi ac lectus convallis cursus eu nec ligula. Proin tristique est vel massa scelerisque tristique. Ut malesuada placerat congue. Sed pretium fermentum ligula, ut ultrices felis faucibus eu.

Sed at lacus nibh, a interdum eros. In sit amet felis felis. Sed eget iaculis velit. Etiam sollicitudin pretium nunc et fringilla. Nunc ligula lorem, accumsan vel porta at, porttitor quis felis. Etiam cursus elit at velit pretium sit amet gravida enim tincidunt. Phasellus laoreet tellus neque. Duis ac nibh sit amet lorem ullamcorper accumsan sit amet pharetra felis. Fusce fermentum purus lacus, eget interdum ante.

Etiam sed dui quis dolor tincidunt eleifend. Morbi vitae tortor eget nisi tristique dictum. Vivamus sit amet faucibus ante. Sed molestie lectus vel tortor mollis placerat. Mauris iaculis congue orci eget eleifend. Morbi risus tellus, sodales pellentesque malesuada vitae, tempus id enim. Etiam sed sem magna. Nam porttitor laoreet eros eget ullamcorper. Sed vulputate aliquet neque in malesuada. Praesent commodo, quam non sagittis tincidunt, leo tellus sollicitudin sem, sagittis suscipit nisl dolor et urna.

Vestibulum eget ante sapien, vel venenatis massa. Quisque sollicitudin tristique purus id rutrum. Integer at risus non ipsum dictum facilisis id sed erat. Donec dictum mauris et neque vehicula ac fermentum nisl sodales. Praesent accumsan venenatis nibh. Cras ac sollicitudin neque. Vivamus ornare dolor eu nulla posuere ut vehicula massa vulputate. Ut sit amet sapien in magna semper feugiat. Suspendisse rutrum scelerisque laoreet. In ac nisi vehicula nisi congue vulputate non in purus. Sed lacus justo, sodales ac tincidunt convallis, sodales vitae mauris. Duis tortor justo, condimentum quis faucibus eu, fermentum eget leo. Nunc hendrerit nisl vel urna accumsan in placerat libero faucibus. Sed vitae risus nec augue tincidunt aliquam sed a enim. Sed a tempus ligula. Donec dignissim tristique adipiscing.

Maecenas quis convallis lacus. In eget metus ligula. Vivamus interdum turpis ac mauris feugiat ac faucibus nisi dignissim. Maecenas malesuada pellentesque diam vel euismod. Nam volutpat, tortor ut lacinia varius, purus diam hendrerit augue, non fermentum enim quam sed nisl. Donec eget massa diam, a aliquet neque. Praesent tincidunt, ligula eu bibendum sodales, sapien lectus porttitor nisl, sit amet fringilla ante magna in nulla. Ut faucibus suscipit ligula, at cursus quam congue nec. Nulla quam tortor, pretium at faucibus id, pulvinar at urna. Integer elementum tortor non libero varius in euismod leo eleifend. Phasellus mattis consequat tristique. Quisque non lacus eu quam porta molestie at ut tellus. Fusce iaculis mi ut quam egestas in cursus turpis congue. Donec tristique ornare enim, et mattis lorem luctus at. Nulla fermentum eros ac turpis sollicitudin quis tincidunt lorem venenatis. Phasellus quis odio velit.

Maecenas et urna sit amet risus commodo molestie vel eu felis. Ut faucibus hendrerit nisi, sit amet volutpat purus ullamcorper vel. Vestibulum arcu ligula, gravida vel tempor quis, bibendum ultrices metus. Morbi varius dui sit amet mi dictum malesuada. Fusce et ullamcorper tortor. Nam arcu tellus, dignissim id feugiat quis, pharetra eget nibh. Nullam justo erat, lacinia id mollis sit amet, venenatis in dui. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Maecenas sit amet dolor vitae lacus imperdiet posuere ornare eget ante. In ultricies lacinia mauris ut egestas. Sed viverra, urna at pellentesque pharetra, urna magna tincidunt augue, a lacinia odio dui quis odio. Aliquam erat volutpat. Quisque fermentum feugiat egestas. Quisque rutrum ultrices facilisis. Nam vitae orci non justo ullamcorper rhoncus.

Phasellus blandit vestibulum aliquet. In volutpat, urna non interdum porta, dui lacus tempor dui, eu pellentesque nisl lorem nec tellus. Suspendisse gravida, sem et aliquet euismod, lacus erat facilisis diam, egestas fringilla massa mi auctor augue. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. In sit amet tortor a lorem vestibulum pellentesque. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Integer tempus lorem non purus tristique tristique. In bibendum nulla enim. Praesent interdum, justo vitae cursus malesuada, urna lacus eleifend eros, eu consectetur nunc quam eu mi. Fusce ipsum est, molestie at pellentesque sit amet, rutrum at libero. Donec hendrerit mattis massa, eget fringilla orci pretium quis. Fusce fringilla placerat pharetra. Proin varius laoreet ullamcorper. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.

Vestibulum tincidunt lectus et nisi mattis vitae vulputate magna hendrerit. Fusce sodales, dolor in sodales elementum, arcu eros fringilla turpis, sed viverra mauris diam id tellus. Pellentesque eget mollis nisl. Suspendisse lacus metus, aliquam in ornare sed, eleifend euismod libero. Praesent nec odio orci. Phasellus pretium neque in ipsum suscipit tincidunt. Aenean id viverra lectus. Integer sagittis, nulla vitae mattis convallis, enim nisi sodales tortor, in venenatis libero nisi eget augue. Nam ut semper quam. Nunc arcu orci, ultrices sit amet rhoncus quis, condimentum non neque. Nunc dictum vehicula neque, ut tincidunt nisi vehicula vel. Cras malesuada nisi consectetur lorem varius pellentesque. Nam mauris mi, gravida et eleifend in, gravida pretium mauris. Aenean rutrum nisi a lectus consequat auctor.

Aenean suscipit odio nec enim semper pharetra. Proin lobortis augue at lectus suscipit laoreet sit amet nec velit. Etiam eu risus sed dui rutrum blandit. Aliquam commodo sodales massa, nec pulvinar elit rhoncus ac. Cras sollicitudin sollicitudin velit, sit amet tincidunt nisl fermentum ut. Ut a est vel ante volutpat tristique eget in tortor. Sed nec mi et neque lacinia tempus eu id lacus. Praesent tincidunt tincidunt dui, quis pharetra urna accumsan sed.

Pellentesque ac diam non odio blandit ullamcorper nec ac orci. Morbi eu sapien sit amet erat interdum egestas a non erat. Suspendisse consequat velit eget sem posuere non venenatis tellus dapibus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vivamus faucibus nisi a felis sollicitudin eget dictum nisl lobortis. Morbi vitae sagittis ante. Nullam sit amet dapibus purus. Fusce convallis dapibus nisl at hendrerit. In hac habitasse platea dictumst. Maecenas faucibus metus luctus sapien tincidunt cursus. Sed at augue dolor. Curabitur condimentum, risus nec egestas bibendum, tortor erat ultrices massa, vel sollicitudin nibh erat vitae dolor.

Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Aliquam erat volutpat. Ut dapibus condimentum mauris ac aliquet. Aenean at arcu velit, quis pellentesque turpis. Vivamus elementum lacinia eros in porttitor. Ut aliquam mauris non nulla pulvinar iaculis. Maecenas eget faucibus nisi. Curabitur rutrum ultrices pharetra. In rutrum vulputate sapien vel eleifend. Sed id feugiat ante. Quisque viverra arcu eget nunc vestibulum a lobortis velit dignissim. Pellentesque vitae velit tempus diam venenatis consectetur. Sed nec risus sit amet purus semper dictum in non purus. Curabitur semper, enim et semper mattis, mauris elit rutrum risus, vitae sollicitudin orci nibh eget urna. Quisque at dapibus sapien. Maecenas turpis justo, pellentesque nec fermentum vel, tristique sed tortor.

Morbi in consectetur tellus. Maecenas id justo non orci suscipit placerat. Duis lectus diam, tincidunt sed convallis a, malesuada id diam. Sed vestibulum cursus leo. Vivamus egestas mauris non elit porttitor a ornare dui placerat. Vivamus eu ligula ut massa gravida adipiscing ac in velit. Vestibulum nec ligula lectus, eu ornare sapien. Vestibulum vel quam et nulla cursus ornare sit amet vel augue. Aenean quis lacus nisi. Ut vestibulum tempus lectus sit amet eleifend. Duis sit amet metus eu nisl lacinia fringilla sit amet a tortor. Quisque tristique justo eget massa tempor id pharetra lacus elementum.

Ut at diam et arcu egestas pulvinar. Aliquam tincidunt nisl et libero elementum id suscipit nulla fringilla. Mauris velit sem, pharetra nec luctus nec, ullamcorper id felis. Ut tempus congue diam in sodales. Pellentesque non elit eros. Vivamus sit amet lorem a eros pellentesque euismod ac ut urna. Donec vitae nulla venenatis tellus dignissim fermentum. Donec congue porttitor massa, in egestas massa fermentum vel. Mauris suscipit porttitor fermentum. Phasellus arcu ligula, mattis ac auctor et, sollicitudin cursus lectus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Cras mattis fringilla nisi, vitae molestie ante facilisis ornare. Pellentesque ligula arcu, ultricies eget hendrerit sed, fermentum egestas libero. Mauris porta condimentum feugiat. Nulla facilisi.

Quisque tempor, nisl in porta pretium, mauris purus volutpat lectus, a condimentum ante odio eu diam. Sed augue diam, pellentesque nec pellentesque at, lacinia sed ante. In mollis facilisis vestibulum. Pellentesque vel tortor at arcu laoreet consectetur at in libero. Donec vitae ligula lacus. Pellentesque non ultricies arcu. Aliquam volutpat facilisis dictum. Morbi cursus varius scelerisque. Aliquam dictum mauris nec turpis tincidunt non iaculis leo mollis. Integer luctus sapien non metus ullamcorper ut laoreet est laoreet. Donec feugiat mattis lectus, et tristique tortor malesuada at. Maecenas rhoncus libero nec diam lobortis auctor. Praesent dapibus pulvinar pellentesque.

Sed luctus fermentum velit at sagittis. Nunc placerat semper sagittis. Donec sit amet mi at turpis posuere aliquet id vel sapien. Nunc at ligula eget erat sagittis ultrices at sed erat. Cras vitae sem ut neque fermentum consectetur. Suspendisse eros dolor, posuere in eleifend id, ullamcorper iaculis mauris. Cras luctus augue vel felis dignissim venenatis.

Curabitur ut elit ac sapien congue lacinia at sit amet metus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Ut non odio eget sem elementum sodales. Etiam auctor consectetur lacus, at elementum erat hendrerit eget. Suspendisse sed leo in massa rutrum malesuada in eget urna. Nunc ac magna justo, non venenatis sem. Sed eu enim metus, at consectetur ipsum. In vel est tellus, at egestas purus. Cras tempus varius metus, sed ullamcorper sem cursus eu. Nullam a turpis enim, vel volutpat mauris. Praesent dapibus facilisis dolor, sed laoreet nunc tristique quis. Curabitur non viverra augue. Nullam ornare, lectus a sollicitudin molestie, nibh purus ullamcorper augue, a tincidunt elit massa vel libero. Fusce consequat ligula sed risus commodo non ultrices purus mattis. Sed lacinia mollis est, sollicitudin accumsan magna gravida eu. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.

Pellentesque aliquet sodales felis sed bibendum. Vestibulum eleifend odio id tortor vehicula posuere. Suspendisse vel sem mi, ac pulvinar ipsum. Sed id felis ante, eu convallis erat. Etiam ac faucibus lectus. Ut euismod, leo sit amet porttitor lacinia, orci est aliquet eros, vel scelerisque elit nulla vel neque. Curabitur sed sapien nunc. Nunc consectetur sagittis arcu sed vestibulum. Aenean suscipit malesuada interdum. Nulla facilisi. Mauris nec tortor sed sem condimentum egestas.

Nulla facilisi. Nam quis ultricies leo. Sed eu mauris lorem. Quisque at nibh ligula. Ut non ante quis felis molestie scelerisque. Praesent vitae bibendum libero. Sed augue leo, sollicitudin a viverra consequat, rhoncus in dolor. Nulla condimentum, sem vel vehicula pretium, massa nulla volutpat erat, non malesuada mauris diam at diam. Praesent a eros leo.

Donec molestie nulla a orci convallis congue. Quisque auctor, lorem sed ultrices congue, nisl est pellentesque nunc, ut aliquam sapien turpis quis metus. Phasellus sed ipsum dui, at sollicitudin dui. In augue sem, molestie vitae sollicitudin gravida, elementum vitae urna. Pellentesque malesuada, felis eu porttitor eleifend, nulla neque luctus nulla, vitae pellentesque magna urna nec nulla. Pellentesque suscipit condimentum mauris, sit amet tempus diam pharetra et. Duis malesuada velit id urna gravida aliquet. Curabitur iaculis leo quis nisl porta ut accumsan urna rhoncus. Ut sed egestas diam. Nulla lobortis, tortor sit amet rutrum aliquam, tortor felis fermentum odio, non eleifend purus leo sit amet est. Vivamus sit amet eros odio.

Curabitur molestie, elit ut eleifend imperdiet, lacus nulla cursus est, vel tristique purus lorem at massa. Suspendisse tristique commodo lobortis. Morbi cursus tempus metus vitae mollis. Curabitur laoreet magna a erat luctus sed volutpat risus dictum. Aliquam nisl nisl, porta a placerat ut, eleifend eget sem. Sed sem ipsum, molestie in porttitor ut, semper vel leo. Nam ac mattis sapien. Proin aliquet laoreet volutpat. Maecenas lobortis iaculis dolor, quis porta purus consequat ut. 

EOS;


$txt_len = strlen($text);
$cmp_len = 20;

$txt_1 = substr($text, 0, $cmp_len);
$cmp_1 = strtoupper($txt_1);
printf("#1: Compare '%s' to '%s'\n", $txt_1, $cmp_1);
$idx_2 = rand(0, $txt_len - $cmp_len);
$txt_2 = substr($text, $idx_2, $cmp_len);
$cmp_2 = strtoupper($txt_2);
printf("#2: Compare '%s' to '%s'\n", $txt_2, $cmp_2);
$idx_3 = rand(0, $txt_len - $cmp_len);
$txt_3 = substr($text, $idx_3, $cmp_len);
$cmp_3 = strtoupper($txt_3);
printf("#3: Compare '%s' to '%s'\n", $txt_3, $cmp_3);
$idx_4 = $txt_len - $cmp_len;
$txt_4 = substr($text, $idx_4, $cmp_len);
$cmp_4 = strtoupper($txt_4);
printf("#4: Compare '%s' to '%s'\n", $txt_4, $cmp_4);


$timer = new Benchmark_Timer();
$nb_iterations = 1000;
$timer->start();

echo "cmp\n";
$r = array();
for ($i = 0; $i < $nb_iterations; $i++) {
  $r[0] = cmp($cmp_1, $text, 0,       $cmp_len);
  $r[1] = cmp($cmp_2, $text, $idx_2,  $cmp_len);
  $r[2] = cmp($cmp_3, $text, $idx_3,  $cmp_len);
  $r[3] = cmp($cmp_4, $text, $idx_4,  $cmp_len);
}
var_dump($r);
$timer->setMarker('cmp');

echo "cmp_pcre\n";
$r = array();
for ($i = 0; $i < $nb_iterations; $i++) {
  $r[0] = cmp_pcre($cmp_1, $text, 0);
  $r[1] = cmp_pcre($cmp_2, $text, $idx_2);
  $r[2] = cmp_pcre($cmp_3, $text, $idx_3);
  $r[3] = cmp_pcre($cmp_4, $text, $idx_4);
}
var_dump($r);
$timer->setMarker('cmp_pcre');

echo "cmp_u\n";
$r = array();
for ($i = 0; $i < $nb_iterations; $i++) {
  $r[0] = cmp_u($cmp_1, $text, 0,       $cmp_len);
  $r[1] = cmp_u($cmp_2, $text, $idx_2,  $cmp_len);
  $r[2] = cmp_u($cmp_3, $text, $idx_3,  $cmp_len);
  $r[3] = cmp_u($cmp_4, $text, $idx_4,  $cmp_len);
}
var_dump($r);
$timer->setMarker('cmp_u');

echo "cmp_pcre_u\n";
$r = array();
for ($i = 0; $i < $nb_iterations; $i++) {
  $r[0] = cmp_pcre_u($cmp_1, $text, 0);
  $r[1] = cmp_pcre_u($cmp_2, $text, $idx_2);
  $r[2] = cmp_pcre_u($cmp_3, $text, $idx_3);
  $r[3] = cmp_pcre_u($cmp_4, $text, $idx_4);
}
var_dump($r);
$timer->setMarker('cmp_pcre_u');


echo $timer->getOutput();
